# Generated by Django 4.0.4 on 2026-10-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_otpcode_otpcode_users_otpco_phone_a31826_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='security_code',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='sent',
        ),
    ]
