# Generated by Django 4.0.4 on 2026-10-01 08:29

from django.db import migrations, models
import sitecontent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('audio_data', models.BinaryField()),
                ('content_type', models.CharField(default='audio/mpeg', max_length=50)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('volume', models.DecimalField(decimal_places=2, default=0.4, help_text='Playback volume between 0 and 1.', max_digits=3)),
                ('is_active', models.BooleanField(default=False, help_text='Only one sound plays in the apps; activating one deactivates the others.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Background Sound',
                'verbose_name_plural': 'Background Sounds',
                'ordering': ('-is_active', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=200)),
                ('content', models.TextField(default='Tamaade respects your privacy. We only collect your personal data when you shop with us.\n\n## What we collect\n- Your name, email address and phone number when you create an account or sign in.\n- The products in your cart and your orders.\n- Delivery and billing details you provide at checkout.\n- The payment status returned by our payment provider (Hubtel). We never see or store your card details or mobile money PIN.\n\n## How we use it\n- To manage your cart, process your orders and deliver them.\n- To confirm payments and send you order updates.\n\nWe do not sell your data and we do not use it for anything other than your shopping on Tamaade.\n\n## Deleting your account\nYou can delete your account at any time from your profile, on the website or in the mobile app. Your name, email, phone number, addresses and cart are erased. Paid orders are kept without your personal details, for accounting.\n\n## Contact\nIf you have questions about your data, contact our support team.', help_text='Plain text. Blank line = new paragraph, "## " = heading, "- " = bullet.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
            },
            bases=(sitecontent.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SoundSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_enabled', models.BooleanField(default=True, help_text='Turn background music off for every user.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sound Settings',
                'verbose_name_plural': 'Sound Settings',
            },
            bases=(sitecontent.models.SingletonMixin, models.Model),
        ),
    ]
