# Generated by Django 4.0.4 on 2026-08-19 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('category', models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('payment', 'Payment'), ('cart', 'Cart'), ('email', 'E-mail'), ('sms', 'SMS'), ('integration', 'Integration'), ('other', 'Other')], default='other', max_length=20)),
                ('message', models.CharField(max_length=300)),
                ('detail', models.TextField(blank=True, help_text='Extra context: payload, exception text, etc.')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System event',
                'verbose_name_plural': 'System events',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['category', '-created_at'], name='dashboard_s_categor_138779_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['level', '-created_at'], name='dashboard_s_level_410ed2_idx'),
        ),
    ]
