# Generated by Django 4.0.4 on 2025-10-13 17:05

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=products.models.product_video_path),
        ),
    ]
