# Generated by hand
from django.db import migrations, models
import django.db.models.deletion
import products.models

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_local', models.ImageField(blank=True, null=True, upload_to=products.models.product_image_path)),
                ('url', models.URLField(blank=True, max_length=600, null=True)),
                ('file_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_local', models.FileField(blank=True, null=True, upload_to=products.models.product_video_path)),
                ('url', models.URLField(blank=True, max_length=600, null=True)),
                ('file_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='products.product')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
