# Generated by hand - drop legacy image/video fields if you have migrated data
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_product_images_and_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
    ]
