# Generated by Django 4.0.4 on 2026-08-17 14:36

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_restore_product_image_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.banner_image_path)),
                ('image_url', models.URLField(blank=True, help_text='Used if no image file is uploaded.')),
                ('link', models.CharField(default='/deals', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero banner',
                'verbose_name_plural': 'Hero banners',
                'ordering': ('order', 'id'),
            },
        ),
    ]
