# Generated by Django 4.0.4 on 2026-08-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_herobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Price tier',
                'verbose_name_plural': 'Price tiers',
                'ordering': ('order', 'amount'),
            },
        ),
        migrations.CreateModel(
            name='StorefrontPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('highlight', models.CharField(blank=True, max_length=120)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('link', models.CharField(default='/deals', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Storefront promo',
                'verbose_name_plural': 'Storefront promos',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount. Leave empty if the product is not on promo.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_express',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_label',
            field=models.CharField(blank=True, help_text='Shown on the product card, e.g. "UP TO 70% OFF".', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
