# Generated by Django 4.0.4 on 2026-08-17 15:03

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_pricetier_storefrontpromo_product_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('main', 'Main grid'), ('featured', 'Featured row'), ('bottom', 'Bottom grid')], default='main', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.merch_tile_image_path)),
                ('image_url', models.URLField(blank=True)),
                ('link', models.CharField(default='/products', max_length=500)),
                ('badge', models.CharField(blank=True, max_length=40)),
                ('highlight', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Merch tile',
                'verbose_name_plural': 'Merch tiles',
                'ordering': ('placement', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('link', models.CharField(max_length=500)),
                ('has_dropdown', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nav link',
                'verbose_name_plural': 'Nav links',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('location', models.CharField(choices=[('home', 'Home'), ('deals', 'Deals')], default='home', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('cta_label', models.CharField(default='View More', max_length=80)),
                ('link', models.CharField(default='/products', max_length=500)),
                ('product_source', models.CharField(choices=[('newest', 'Newest'), ('featured', 'Featured'), ('bestsellers', 'Bestsellers')], default='featured', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home section',
                'verbose_name_plural': 'Home sections',
                'ordering': ('location', 'order', 'id'),
                'unique_together': {('location', 'key')},
            },
        ),
    ]
